// ============================================================
// html-report.test.ts — report/preview HTML on the canonical embed block.
//
// Since BL-114 the per-diagram chrome (hover toolbar, hidden source panel,
// copy / open-in-editor, error card, highlight roles) comes from
// @diagrammo/dgmo/block — these tests pin the report generator to that
// standard markup vocabulary (figure.dgmo, .dgmo-source-wrap, .dgmo--error)
// and guard the report-local chrome (title/TOC/footer/theme) around it.
// ============================================================

import { describe, it, expect } from 'vitest';
import { getPalette } from '@diagrammo/dgmo/advanced';
import { buildPreviewHtml, buildReportHtml } from '../src/html-report.js';
import type { ReportSection } from '../src/html-report.js';

const palette = getPalette('slate');
const SVG = '<svg viewBox="0 0 100 50"><rect width="10" height="10"/></svg>';
const SOURCE = 'bar Revenue\n\nNorth 850\nSouth 620';

function section(overrides: Partial<ReportSection> = {}): ReportSection {
  return { title: 'Revenue', svg: SVG, dgmoSource: SOURCE, ...overrides };
}

describe('buildReportHtml — canonical embed block per section', () => {
  const html = buildReportHtml({
    title: 'Q3 Report',
    sections: [section()],
    palette,
    includeSource: true,
  });

  it('wraps each diagram in the standard showcase block', () => {
    expect(html).toContain('class="dgmo dgmo--showcase"');
    expect(html).toContain('<details class="dgmo-source-wrap">');
    expect(html).toContain('summary class="dgmo-toolbar"');
    expect(html).toContain('class="dgmo-toolbar-btn dgmo-copy"');
  });

  it('carries the raw source on the copy button', () => {
    expect(html).toContain('data-dgmo-source="bar Revenue');
  });

  it('uses the section title as the block aria-label', () => {
    expect(html).toContain('aria-label="Revenue"');
  });

  it('inlines BLOCK_CSS so the report stays self-contained', () => {
    // .dgmo-tok-* rules only exist in the block stylesheet.
    expect(html).toContain('.dgmo-tok-keyword');
  });

  it('emits no bespoke legacy chrome', () => {
    expect(html).not.toContain('diagram-wrapper');
    expect(html).not.toContain('error-placeholder');
    expect(html).not.toContain('copy-btn');
  });

  it('keeps report-level chrome (title, footer)', () => {
    expect(html).toContain('<h1>Q3 Report</h1>');
    expect(html).toContain('Generated by Diagrammo');
  });

  it('defaults to the light theme (aligned with render_diagram + core block)', () => {
    expect(html).toContain('data-theme="light"');
  });
});

describe('buildReportHtml — source visibility and errors', () => {
  it('includeSource: false → diagram-only block, no source chrome', () => {
    const html = buildReportHtml({
      title: 'Report',
      sections: [section()],
      palette,
      includeSource: false,
    });
    expect(html).toContain('class="dgmo dgmo--diagram"');
    // (the class still appears in the inlined BLOCK_CSS — assert on markup)
    expect(html).not.toContain('<details class="dgmo-source-wrap">');
  });

  it('failed section → standard error card with role="alert"', () => {
    const html = buildReportHtml({
      title: 'Report',
      sections: [section({ svg: null, error: 'boom at line 2' })],
      palette,
      includeSource: true,
    });
    expect(html).toContain('dgmo--error');
    expect(html).toContain('role="alert"');
    expect(html).toContain('boom at line 2');
  });

  it('theme: dark flips the page data-theme', () => {
    const html = buildReportHtml({
      title: 'Report',
      sections: [section()],
      palette,
      includeSource: true,
      theme: 'dark',
    });
    expect(html).toContain('data-theme="dark"');
  });

  it('more than 3 sections → table of contents', () => {
    const html = buildReportHtml({
      title: 'Report',
      sections: [1, 2, 3, 4].map((n) => section({ title: `S${n}` })),
      palette,
      includeSource: true,
    });
    expect(html).toContain('class="toc"');
    expect(html).toContain('href="#section-0"');
  });
});

describe('buildPreviewHtml', () => {
  it('renders the standard showcase block with the share link', () => {
    const html = buildPreviewHtml({
      svg: SVG,
      title: 'My Diagram',
      dgmoSource: SOURCE,
      palette,
      shareUrl: 'https://diagrammo.app/#abc',
    });
    expect(html).toContain('class="dgmo dgmo--showcase"');
    expect(html).toContain('aria-label="My Diagram"');
    expect(html).toContain('https://diagrammo.app/#abc');
    expect(html).toContain('data-theme="light"');
  });

  it('omits source chrome when no source is provided', () => {
    const html = buildPreviewHtml({ svg: SVG, palette });
    expect(html).toContain('class="dgmo dgmo--diagram"');
    // (the class still appears in the inlined BLOCK_CSS — assert on markup)
    expect(html).not.toContain('<details class="dgmo-source-wrap">');
  });
});
