// Trigger phrases keyed by chart-type id — the natural-language vocabulary
// the suggester matches. Lives here (dgmo-mcp), NOT in the dgmo render library:
// chart-type SELECTION is AI-authoring functionality only this server needs.
// Keyed by id; validated against @diagrammo/dgmo chartTypes by suggest.test.ts.
export const TRIGGERS: Record<string, readonly string[]> = {
  "journey-map": ["user journey", "customer journey", "customer experience", "customer goes through", "user goes through", "customer path", "customer touchpoints", "cx flow", "ux journey", "onboarding flow", "persona journey", "empathy map", "service blueprint"],
  c4: ["c4 diagram", "system context", "container diagram", "component diagram", "architecture overview", "software architecture", "microservices", "microservice architecture"],
  er: ["database schema", "er diagram", "entity relationship", "data model", "tables and relationships", "foreign keys"],
  class: ["uml class", "class hierarchy", "class diagram", "inheritance tree", "oop structure"],
  sequence: ["sequence diagram", "message flow", "api call flow", "request lifecycle", "interaction diagram", "call sequence", "login flow", "authentication flow", "logging in", "request flow", "oauth", "oauth flow"],
  state: ["state diagram", "state machine", "state transitions", "lifecycle diagram", "status transitions", "order states", "states from", "order lifecycle"],
  infra: ["infrastructure diagram", "traffic flow", "request path", "rps", "capacity planning", "network topology"],
  gantt: ["gantt chart", "project schedule", "sprint plan", "project timeline", "project milestones"],
  pert: ["pert chart", "pert diagram", "project network", "critical path method", "monte carlo schedule", "schedule risk", "estimate uncertainty", "project simulation", "task dependencies", "task dependency network"],
  timeline: ["event timeline", "historical timeline", "era chart", "period chart", "project history", "timeline", "milestone timeline", "milestones", "roadmap", "product roadmap"],
  org: ["org chart", "organization chart", "reporting structure", "hierarchy chart", "team structure", "reports to", "who reports to"],
  sitemap: ["sitemap", "site structure", "page hierarchy", "navigation structure", "app navigation", "website pages", "site pages", "api endpoints"],
  kanban: ["kanban board", "task board", "workflow columns", "todo doing done", "agile board"],
  raci: ["raci", "raci matrix", "responsibility matrix", "responsibility assignment", "who does what", "accountability matrix"],
  rasci: ["rasci", "rasci matrix", "support roles matrix"],
  daci: ["daci", "daci matrix", "decision matrix", "decision tracking", "driver approver"],
  "tech-radar": ["tech radar", "technology radar", "tech adoption", "adopt trial assess hold", "tech choices"],
  mindmap: ["mind map", "brainstorm diagram", "concept map", "idea tree", "radial ideas"],
  wireframe: ["wireframe", "ui mockup", "screen layout", "page layout", "low-fidelity mockup"],
  cycle: ["pdca cycle", "ooda loop", "feedback loop", "cyclical process", "devops loop", "continuous loop", "cycle diagram"],
  pyramid: ["pyramid diagram", "layered hierarchy", "maslow hierarchy", "dikw pyramid", "layered model"],
  ring: ["ring diagram", "concentric rings", "circle hierarchy", "circles of influence", "nested circles"],
  map: ["world map", "us states map", "choropleth map", "geographic map", "map of countries", "map with cities", "store locations", "office locations", "locations worldwide", "located", "worldwide"],
  quadrant: ["quadrant", "2x2 matrix", "priority matrix", "quadrant chart", "impact effort matrix", "effort versus impact", "positioning matrix"],
  venn: ["venn diagram", "set overlap", "intersection of", "shared traits", "overlapping circles"],
  funnel: ["funnel", "conversion funnel", "sales funnel", "user funnel", "pipeline stages", "drop-off funnel", "sales pipeline"],
  slope: ["slope chart", "before and after", "two-period change", "delta chart", "shift comparison"],
  sankey: ["sankey diagram", "flow allocation", "budget flow", "energy flow", "traffic allocation"],
  chord: ["chord diagram", "circular flow", "relationship wheel", "team connections", "trade flows", "flows between countries"],
  arc: ["arc diagram", "relationship chart", "connection arcs", "network arcs"],
  wordcloud: ["word cloud", "tag cloud", "term frequency", "keyword frequency", "common words"],
  heatmap: ["heatmap", "intensity matrix", "activity heatmap", "correlation matrix"],
  function: ["function plot", "mathematical plot", "equation chart", "graph y=f(x)"],
  bar: ["bar chart", "categorical comparison", "bar graph", "revenue by region", "revenue by", "quarterly revenue", "quarterly sales", "q1 q2 q3 q4"],
  line: ["line chart", "trend over time", "time series", "sales trend", "sales over time"],
  "multi-line": ["multi-line chart", "multiple trends", "multiple series over time"],
  area: ["area chart", "filled line", "cumulative trend"],
  pie: ["pie chart", "part to whole", "percentage breakdown", "market share"],
  doughnut: ["doughnut chart", "donut chart", "ring chart"],
  radar: ["radar chart", "spider chart", "multi-dimensional metrics", "team skills", "skills comparison"],
  "polar-area": ["polar area", "radial bar chart"],
  "bar-stacked": ["stacked bar", "stacked bar chart", "multi-series bar", "composite bar"],
  scatter: ["scatter plot", "correlation plot", "bubble chart", "2d data points", "correlation between"],
  flowchart: ["flowchart", "flow chart", "decision tree", "if-then diagram", "process flow with decisions", "process flow"],
  "boxes-and-lines": ["boxes and lines", "boxes and arrows", "nodes and edges", "generic diagram", "general-purpose network"],
};
