// ============================================================
// main.ts — the guidance studio's single linear screen (no framework, plain
// TS + DOM, matching the selection-harness precedent).
//
// ONE loop, top→bottom: pick a type → edit its TIPS → Run a prompt (+dataset) →
// see DGMO source + rendered image + a manual tips-checklist + the exact
// injected guidance → Save (validated). The type picker doubles as the coverage
// progress bar (has-tips/empty). Phase-2 extras (N=3 before/after compare,
// per-type dataset defaulting) layer on without disturbing the core loop.
// ============================================================
import registry from './registry.json';
import prompts from './prompts.json';
import promptValidation from './prompt-validation.json';

// Per-type starter prompts (generated by datasets/build.mjs) — each type maps
// to a LIST of prompts; [0] is dataset-grounded, the rest are self-contained
// scenarios. Falls back to a generic single-entry list for any unmapped type.
const defaultPrompts = prompts as Record<string, string[]>;

// Persisted prompt-validation record (committed prompt-validation.json) — the
// outcome of the validation pass: each starter prompt was authored, parsed
// through the render gate, rendered, and intent-judged. Keyed by EXACT prompt
// text so it survives reordering and flags edited prompts as unvalidated.
interface PromptVerdict {
  prompt: string;
  valid: boolean;
  render: string;
  intent: 'good' | 'weak' | 'no';
}
const validationMeta = (promptValidation as { _meta?: { validatedOn?: string } })
  ._meta;
const validationByPrompt = new Map<string, PromptVerdict>();
for (const [k, v] of Object.entries(promptValidation as Record<string, unknown>)) {
  if (k === '_meta') continue;
  for (const verdict of v as PromptVerdict[])
    validationByPrompt.set(verdict.prompt, verdict);
}
/** Glyph + human label for a prompt's validation status (by exact text). */
function validationStatus(promptText: string): { glyph: string; label: string } {
  const v = validationByPrompt.get(promptText.trim());
  if (!v)
    return { glyph: '•', label: 'not yet validated (edited or new prompt)' };
  if (!v.valid || v.render !== 'ok')
    return { glyph: '✗', label: 'failed validation — does not parse/render' };
  if (v.intent !== 'good')
    return { glyph: '⚠', label: `validated, but intent ${v.intent}` };
  const on = validationMeta?.validatedOn ? ` ${validationMeta.validatedOn}` : '';
  return { glyph: '✓', label: `validated${on} — parses, renders, intent good` };
}

// Pre-rendered gallery (built by build-gallery.mjs, served at /studio/gallery):
// the persisted DGMO + render for every type × starter prompt, so a prompt can
// be inspected WITHOUT a live `claude -p` run. Fetched once and cached.
interface GalleryEntry {
  idx: number;
  prompt: string;
  dgmo: string;
  img: string | null;
  valid: boolean;
  intent: string;
  render: string;
  error: string | null;
}
let galleryCache: Record<string, GalleryEntry[]> | null = null;
async function loadGallery(): Promise<Record<string, GalleryEntry[]>> {
  if (galleryCache) return galleryCache;
  try {
    galleryCache = (await fetch('/studio/gallery').then((r) => r.json())) as Record<
      string,
      GalleryEntry[]
    >;
  } catch {
    galleryCache = {};
  }
  return galleryCache ?? {};
}

interface TypeEntry {
  id: string;
  description: string;
  hasTips: boolean;
}
interface DatasetMeta {
  id: string;
  label: string;
  suitsTypes: string[];
}
interface RunResult {
  dgmo: string;
  svg: string | null;
  pngBase64: string | null;
  resolvedPrompt: string;
  injectedTips: string;
  diagnostics: { severity: string; message: string }[];
  error: string | null;
}

const types: TypeEntry[] = (registry as { types: TypeEntry[] }).types;

const $ = <T extends HTMLElement = HTMLElement>(sel: string): T =>
  document.querySelector(sel) as T;
// props is a loose bag assigned onto the element (value/type/style strings etc.
// are valid at runtime for the specific element kinds we create).
const el = (tag: string, props: Record<string, unknown> = {}, html?: string): HTMLElement => {
  const e = document.createElement(tag);
  Object.assign(e, props);
  if (html != null) e.innerHTML = html;
  return e;
};

const state = {
  type: null as string | null,
  savedTips: '', // last on-disk block, to detect unsaved edits
  datasets: [] as DatasetMeta[],
};

// Last single-Run result per (type, prompt), kept in memory so switching chart
// types OR prompts doesn't throw away a `claude -p` run. Keyed `type::idx` so
// each prompt row keeps its own run — clicking away and back restores it
// instead of falling back to the persisted gallery. `sig` captures the inputs
// that produced it (prompt + dataset + tips); if those later differ, the
// restored result is flagged stale rather than silently misleading.
//
// This map is persisted server-side to trial-runs.json: every Run upserts its
// (type, idx) entry, and the map is hydrated from that file on load — so a hand-
// run diagram survives a page refresh (and a dev-server restart) instead of
// snapping back to the baseline gallery.
const lastRuns = new Map<string, { result: RunResult; sig: string }>();

/** Persist one manual run so it survives a reload (fire-and-forget). The svg is
 *  dropped before persisting — display uses the base64 PNG, and svg is large. */
function persistTrial(
  type: string,
  idx: number,
  promptText: string,
  sig: string,
  result: RunResult
): void {
  void fetch('/studio/trials', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      type,
      idx,
      prompt: promptText,
      sig,
      result: { ...result, svg: null },
    }),
  }).catch(() => {
    /* dev tool — a failed persist just means this run is in-memory only */
  });
}

/** Hydrate lastRuns from the persisted trial store (called once at boot). */
async function hydrateTrials(): Promise<void> {
  try {
    const store = (await fetch('/studio/trials').then((r) => r.json())) as Record<
      string,
      Record<string, { sig?: string; result?: RunResult }>
    >;
    for (const [type, byIdx] of Object.entries(store)) {
      for (const [idx, rec] of Object.entries(byIdx)) {
        if (rec?.result)
          lastRuns.set(`${type}::${idx}`, { result: rec.result, sig: rec.sig ?? '' });
      }
    }
  } catch {
    /* dev tool — no persisted trials yet */
  }
}
const trialsReady = hydrateTrials();

// Per-type prompt + dataset choice, remembered browser-locally (runs stay
// ephemeral — only TIPS persist to disk; this just stops a crafted prompt from
// resetting on reload/tab-switch). Keyed by chart type.
const PREFS_KEY = 'dgmo-studio-prompts';
type Pref = { prompt?: string; datasetId?: string; promptIdx?: number };
function loadPrefs(): Record<string, Pref> {
  try {
    return JSON.parse(localStorage.getItem(PREFS_KEY) ?? '{}');
  } catch {
    return {};
  }
}
function savePref(type: string, pref: Pref): void {
  try {
    const all = loadPrefs();
    all[type] = { ...all[type], ...pref };
    localStorage.setItem(PREFS_KEY, JSON.stringify(all));
  } catch {
    /* storage disabled — degrade to ephemeral */
  }
}

// ---- picker ----------------------------------------------------------------
const picker = $('#picker');
function renderPicker(): void {
  picker.innerHTML = '';
  const withTips = types.filter((t) => t.hasTips).length;
  picker.appendChild(
    el('div', { className: 'count' }, `${withTips} / ${types.length} types have tips`)
  );
  for (const t of types) {
    const btn = el('button', { title: t.description }) as HTMLButtonElement;
    if (t.id === state.type) btn.classList.add('active');
    btn.appendChild(el('span', { className: `dot ${t.hasTips ? 'has' : 'empty'}` }));
    btn.appendChild(el('span', {}, t.id));
    btn.onclick = () => selectType(t.id);
    picker.appendChild(btn);
  }
}

async function refreshCoverage(): Promise<void> {
  try {
    const r = await fetch('/studio/coverage').then((x) => x.json());
    const map = new Map<string, boolean>(
      (r.types as { type: string; hasTips: boolean }[]).map((t) => [t.type, t.hasTips])
    );
    for (const t of types) if (map.has(t.id)) t.hasTips = map.get(t.id)!;
    renderPicker();
  } catch {
    /* dev tool — ignore */
  }
}

// ---- work area -------------------------------------------------------------
const work = $('#work');

function emptyState(): void {
  work.innerHTML = '';
  work.appendChild(
    el(
      'div',
      { className: 'empty-state' },
      `<h2>Pick a type to start</h2>
       <p>Choose a chart type on the left. You'll see how the AI is currently told
       to style it (its <b>tips</b>), tweak that guidance, then hit <b>Run</b> with a
       prompt to see the diagram the model produces. Green dots = a type already has tips.</p>`
    )
  );
}

function tipsBodyOf(block: string): string {
  return block
    .replace(/<!--\s*TIPS start\s*-->/, '')
    .replace(/<!--\s*TIPS end\s*-->/, '')
    .trim();
}

// The editor only ever holds the PROSE — both the <!-- TIPS --> anchors AND the
// boilerplate "**Styling tips:**" lead-in are managed here (the lead-in is the
// box's title), so a stray keystroke can't break a marker or mangle the framing
// the model sees.
const TIPS_PREFIX = '**Styling tips:**';
/** Strip the managed lead-in for display in the editor. */
function stripTipsPrefix(body: string): string {
  return body.replace(/^\*\*Styling tips:\*\*\s*/, '').trim();
}
/** Re-attach the managed lead-in (what's saved + what the model is told). */
function composeTips(body: string): string {
  return `${TIPS_PREFIX} ${body.trim()}`;
}
function wrapTips(body: string): string {
  return `<!-- TIPS start -->\n${body.trim()}\n<!-- TIPS end -->`;
}

async function selectType(id: string): Promise<void> {
  state.type = id;
  renderPicker();
  work.innerHTML = '<p class="spinner">Loading…</p>';
  await trialsReady; // ensure persisted runs are in lastRuns before we consult it

  const [guidance, ds] = await Promise.all([
    fetch(`/studio/guidance?type=${encodeURIComponent(id)}`).then((r) => r.json()),
    fetch(`/studio/datasets?type=${encodeURIComponent(id)}`).then((r) => r.json()),
  ]);
  // Edit only the prose — the <!-- TIPS --> markers AND the "Styling tips:"
  // lead-in are managed for you (the lead-in is the box title below).
  const savedBody = stripTipsPrefix(tipsBodyOf(guidance.block));
  state.savedTips = savedBody;
  state.datasets = ds.all;
  const fitting: DatasetMeta[] = ds.fitting;

  work.innerHTML = '';

  // --- tips editor ---
  const tipsSec = el('section');
  tipsSec.appendChild(
    el('label', { className: 'fld' }, `Styling tips — how the AI should style a "${id}"`)
  );
  const tips = el('textarea', { id: 'tips', value: savedBody }) as HTMLTextAreaElement;
  tips.placeholder =
    'e.g. sort bars by value; highlight one series with color; label axes with units';
  tipsSec.appendChild(tips);
  tipsSec.appendChild(
    el(
      'div',
      { className: 'count', style: 'padding:4px 2px 0' },
      'Just the guidance text — the “Styling tips:” lead-in and the <!-- TIPS --> markers are added automatically on save.'
    )
  );
  const saveRow = el('div', { className: 'row', style: 'justify-content:flex-start;margin-top:8px' });
  saveRow.style.flex = 'none';
  const saveBtn = el('button', { className: 'btn', textContent: 'Save tips' }) as HTMLButtonElement;
  saveBtn.style.flex = 'none';
  const unsaved = el('span', { className: 'unsaved', id: 'unsaved' });
  const saveStatus = el('span', { id: 'save-status' });
  saveRow.append(saveBtn, unsaved, saveStatus);
  tipsSec.appendChild(saveRow);
  work.appendChild(tipsSec);

  const markUnsaved = (): void => {
    unsaved.textContent = tips.value !== state.savedTips ? '● unsaved' : '';
    saveStatus.textContent = '';
  };
  tips.oninput = markUnsaved;
  saveBtn.onclick = async () => {
    saveStatus.className = '';
    if (!tips.value.trim()) {
      saveStatus.className = 'saved-bad';
      saveStatus.textContent = 'nothing to save — add some guidance first';
      return;
    }
    saveStatus.textContent = 'Saving…';
    const r = await fetch('/studio/guidance', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ type: id, block: wrapTips(composeTips(tips.value)) }),
    }).then((x) => x.json());
    if (r.ok) {
      state.savedTips = tips.value;
      unsaved.textContent = '';
      saveStatus.className = 'saved-ok';
      saveStatus.textContent = '✓ saved';
      refreshCoverage();
    } else {
      saveStatus.className = 'saved-bad';
      saveStatus.textContent = `✗ rejected: ${r.reason}`;
    }
  };

  // Remembered prompt/dataset for this type (browser-local), if any.
  const pref = loadPrefs()[id] ?? {};

  // --- prompts ---
  const runSec = el('section');
  runSec.appendChild(
    el('label', { className: 'fld' }, 'Prompts — click one to view its saved DGMO + render')
  );

  // Per-type prompt list ([0] dataset-grounded, rest self-contained scenarios).
  // Mutable copy so "+ Add prompt" can append without a reload.
  const typePrompts: string[] = defaultPrompts[id]?.length
    ? [...defaultPrompts[id]]
    : [`Make a ${id} diagram of the sample data.`];
  let activeIdx = Math.min(
    Math.max(pref.promptIdx ?? 0, 0),
    typePrompts.length - 1
  );

  // Cache key for the active prompt's live run (see `lastRuns`).
  const runKey = (): string => `${id}::${activeIdx}`;

  // Editable copy of the active prompt — what Run/Compare actually send (lets
  // you tweak a prompt before a live run without disturbing the saved list).
  const prompt = el('input', {
    id: 'prompt',
    value: pref.prompt ?? typePrompts[activeIdx],
  }) as HTMLInputElement;

  // Clickable prompt list (replaces the old <select>). Each row shows its
  // persisted validation glyph; clicking shows that prompt's saved gallery.
  const promptList = el('div', { className: 'prompt-list', id: 'prompt-list' });
  runSec.appendChild(promptList);

  // Per-prompt validation status (persisted) shown under the edit box; refreshes
  // as the edited prompt text changes (an edit → unvalidated).
  const validNote = el('div', { className: 'count', id: 'prompt-validation', style: 'padding:4px 2px 0' });
  const refreshValidNote = (): void => {
    const { glyph, label } = validationStatus(prompt.value);
    validNote.textContent = `${glyph} ${label}`;
    validNote.style.color =
      glyph === '✓' ? 'var(--good)' : glyph === '•' ? 'var(--muted)' : 'var(--warn)';
  };

  function renderPromptList(): void {
    promptList.innerHTML = '';
    typePrompts.forEach((p, i) => {
      const { glyph } = validationStatus(p);
      const row = el('button', {
        className: 'prompt-row' + (i === activeIdx ? ' active' : ''),
        type: 'button',
      });
      row.appendChild(el('span', { className: 'pglyph' }, glyph));
      row.appendChild(el('span', { className: 'pnum' }, `${i + 1}.`));
      row.appendChild(el('span', {}, p));
      row.onclick = () => selectPrompt(i);
      promptList.appendChild(row);
    });
    // "+ Add prompt" affordance.
    const add = el('button', {
      className: 'prompt-row add',
      type: 'button',
    });
    add.appendChild(el('span', { className: 'pglyph' }, '＋'));
    add.appendChild(el('span', {}, 'Add a prompt for this type…'));
    add.onclick = () => openAddPrompt();
    promptList.appendChild(add);
  }

  // selectPrompt + showGallery + openAddPrompt are declared (hoisted) here but
  // reference resultSec/updateStale defined below — only ever CALLED after the
  // full section is built (initial call is at the end of selectType).
  function selectPrompt(i: number): void {
    activeIdx = i;
    prompt.value = typePrompts[i];
    savePref(id, { promptIdx: i, prompt: typePrompts[i] });
    renderPromptList();
    refreshValidNote();
    // Restore this prompt's prior live run if we have one; else the gallery.
    const cached = lastRuns.get(runKey());
    if (cached) renderSingle(resultSec, cached.result, tips.value);
    else void showGallery(i);
    updateStale();
  }

  async function showGallery(i: number): Promise<void> {
    const g = await loadGallery();
    const entry = g[id]?.[i] ?? null;
    renderGalleryEntry(resultSec, entry, typePrompts[i], id);
  }

  function openAddPrompt(): void {
    const row = el('div', { className: 'row', style: 'margin:4px 0' });
    const inp = el('input', {
      placeholder: `New ${id} prompt — a natural instruction…`,
    }) as HTMLInputElement;
    const addBtn = el('button', {
      className: 'btn narrow',
      textContent: 'Add',
    }) as HTMLButtonElement;
    const cancel = el('button', {
      className: 'btn ghost narrow',
      textContent: 'Cancel',
    }) as HTMLButtonElement;
    const status = el('span', { className: 'count', style: 'flex:none' });
    row.append(inp, addBtn, cancel, status);
    promptList.appendChild(row);
    inp.focus();
    cancel.onclick = () => renderPromptList();
    const submit = async (): Promise<void> => {
      const text = inp.value.trim();
      if (!text) {
        status.textContent = 'enter a prompt first';
        return;
      }
      addBtn.disabled = true;
      status.textContent = 'saving…';
      try {
        const r = await fetch('/studio/prompts', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ type: id, prompt: text }),
        }).then((x) => x.json());
        if (!r.ok) throw new Error(r.reason ?? 'rejected');
        // Adopt the server's authoritative list, keep the in-memory default in
        // sync, then select the new prompt.
        typePrompts.length = 0;
        typePrompts.push(...(r.prompts as string[]));
        defaultPrompts[id] = [...typePrompts];
        selectPrompt(typePrompts.length - 1);
      } catch (err) {
        addBtn.disabled = false;
        status.textContent = `✗ ${String(err)}`;
      }
    };
    addBtn.onclick = submit;
    inp.onkeydown = (e) => {
      if ((e as KeyboardEvent).key === 'Enter') void submit();
    };
  }

  prompt.oninput = () => {
    savePref(id, { prompt: prompt.value });
    refreshValidNote();
    updateStale();
  };
  renderPromptList();
  runSec.appendChild(el('label', { className: 'fld', style: 'margin-top:8px' }, 'Edit the selected prompt (for a live Run)'));
  runSec.appendChild(prompt);
  runSec.appendChild(validNote);
  refreshValidNote();

  const ctl = el('div', { className: 'row', style: 'margin-top:10px' });
  const dsSelect = el('select', { id: 'dataset' }) as HTMLSelectElement;
  dsSelect.appendChild(el('option', { value: '', textContent: 'No dataset' }));
  const dsIds = new Set(state.datasets.map((d) => d.id));
  for (const d of state.datasets) {
    const o = el('option', { value: d.id, textContent: d.label }) as HTMLOptionElement;
    dsSelect.appendChild(o);
  }
  // Remembered choice wins (incl. an explicit "No dataset"); otherwise default
  // to a fitting dataset when one exists (Phase-2 O4); "none" is allowed.
  if (pref.datasetId !== undefined && (pref.datasetId === '' || dsIds.has(pref.datasetId)))
    dsSelect.value = pref.datasetId;
  else if (fitting.length) dsSelect.value = fitting[0].id;
  ctl.appendChild(dsSelect);
  const runBtn = el('button', { className: 'btn narrow', textContent: 'Run' }) as HTMLButtonElement;
  const cmpBtn = el('button', {
    className: 'btn ghost narrow',
    textContent: 'Compare 3× (no-tips vs tips)',
  }) as HTMLButtonElement;
  ctl.append(runBtn, cmpBtn);
  runSec.appendChild(ctl);

  // Live preview of the selected dataset's literal values (what gets injected).
  const dataPreview = el('details', {
    id: 'data-preview',
    style: 'margin-top:10px',
  }) as HTMLDetailsElement;
  runSec.appendChild(dataPreview);
  const showDataset = async (dsId: string): Promise<void> => {
    if (!dsId) {
      dataPreview.innerHTML = '';
      return;
    }
    dataPreview.innerHTML = '';
    dataPreview.appendChild(
      el('summary', {}, `Dataset values injected into the prompt — ${dsId}`)
    );
    const pre = el('pre', {}, 'loading…');
    dataPreview.appendChild(pre);
    dataPreview.open = true;
    try {
      const ds = await fetch(
        `/studio/dataset?id=${encodeURIComponent(dsId)}`
      ).then((r) => r.json());
      pre.textContent = JSON.stringify(ds.data ?? ds, null, 2);
    } catch (err) {
      pre.textContent = `(failed to load dataset: ${String(err)})`;
    }
  };
  dsSelect.onchange = () => {
    savePref(id, { datasetId: dsSelect.value });
    void showDataset(dsSelect.value);
  };
  void showDataset(dsSelect.value); // reflect the initial/remembered choice

  // Stale banner sits above the result so renderSingle (which rebuilds the
  // result body) never clobbers it.
  const staleNote = el(
    'div',
    {
      className: 'count',
      style: 'color:var(--warn);display:none;margin-bottom:6px',
    },
    '⟳ Prompt, dataset, or tips changed since this result — Run again to refresh.'
  );
  runSec.appendChild(staleNote);
  work.appendChild(runSec);

  const resultSec = el('section', { id: 'result' });
  work.appendChild(resultSec);

  // Signature of the inputs that determine a run's output.
  const sigNow = (): string =>
    JSON.stringify({ p: prompt.value, d: dsSelect.value, t: tips.value.trim() });
  const updateStale = (): void => {
    const cached = lastRuns.get(runKey());
    staleNote.style.display =
      cached && resultSec.childElementCount > 0 && cached.sig !== sigNow()
        ? ''
        : 'none';
  };
  prompt.addEventListener('input', updateStale);
  dsSelect.addEventListener('change', updateStale);
  tips.addEventListener('input', updateStale);

  const runOnce = (overrideTips?: string): Promise<RunResult> =>
    fetch('/studio/run', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        type: id,
        prompt: prompt.value,
        datasetId: dsSelect.value || undefined,
        tips:
          overrideTips != null
            ? overrideTips
            : tips.value.trim()
              ? composeTips(tips.value)
              : '',
      }),
    }).then((x) => x.json());

  runBtn.onclick = async () => {
    resultSec.innerHTML = '<p class="spinner">Running claude…</p>';
    try {
      const res = await runOnce();
      renderSingle(resultSec, res, tips.value);
      const sig = sigNow();
      lastRuns.set(runKey(), { result: res, sig });
      persistTrial(id, activeIdx, prompt.value, sig, res);
    } catch (err) {
      resultSec.innerHTML = `<p class="diag">Run failed: ${String(err)}</p>`;
    }
    updateStale();
  };

  cmpBtn.onclick = () => runCompare(resultSec, prompt, dsSelect, tips, id);

  // Show a prior LIVE run if one exists (don't waste it); otherwise show the
  // selected prompt's PERSISTED gallery render so output is visible immediately.
  const cached = lastRuns.get(runKey());
  if (cached) renderSingle(resultSec, cached.result, tips.value);
  else void showGallery(activeIdx);
  updateStale();

  markUnsaved();
}

// ---- single-run result -----------------------------------------------------
function imgEl(pngBase64: string | null): HTMLElement {
  const box = el('div', { className: 'img' });
  if (pngBase64) {
    const img = el('img') as HTMLImageElement;
    img.src = `data:image/png;base64,${pngBase64}`;
    box.appendChild(img);
  } else {
    box.appendChild(el('span', { className: 'spinner', textContent: 'no image' }));
  }
  return box;
}

/** Split tips prose into checklist items (bullets, or sentence-ish clauses). */
function checklistItems(tipsBlockOrBody: string): string[] {
  const body = tipsBodyOf(tipsBlockOrBody).replace(/^\*\*Styling tips:\*\*/, '');
  const bullets = body
    .split('\n')
    .map((l) => l.replace(/^[-*]\s*/, '').trim())
    .filter((l) => l.length > 2);
  if (bullets.length > 1) return bullets;
  // single dense line → split on ; into criteria
  return body
    .split(/;|\.(?:\s|$)/)
    .map((s) => s.trim())
    .filter((s) => s.length > 4);
}

function renderSingle(host: HTMLElement, res: RunResult, tipsBlock: string): void {
  host.innerHTML = '';
  const grid = el('div', { className: 'result' });
  // left: source (with a copy button on the label row)
  const left = el('div');
  const srcHead = el('div', {
    className: 'row',
    style: 'align-items:center;gap:8px',
  });
  srcHead.appendChild(el('label', { className: 'fld', style: 'margin:0' }, 'Generated DGMO'));
  const copyBtn = el('button', {
    className: 'btn ghost narrow',
    textContent: '⧉ Copy',
    title: 'Copy the DGMO source',
    style: 'flex:none;padding:3px 10px',
  }) as HTMLButtonElement;
  copyBtn.disabled = !res.dgmo;
  copyBtn.onclick = async () => {
    try {
      await navigator.clipboard.writeText(res.dgmo);
      copyBtn.textContent = '✓ Copied';
      setTimeout(() => (copyBtn.textContent = '⧉ Copy'), 1200);
    } catch {
      copyBtn.textContent = '✗ Copy failed';
      setTimeout(() => (copyBtn.textContent = '⧉ Copy'), 1500);
    }
  };
  srcHead.appendChild(copyBtn);
  left.appendChild(srcHead);
  left.appendChild(el('pre', { style: 'margin-top:4px' }, escapeHtml(res.dgmo || '(no source)')));
  if (res.error) left.appendChild(el('p', { className: 'diag' }, escapeHtml(res.error)));
  grid.appendChild(left);
  // right: image + checklist
  const right = el('div');
  right.appendChild(el('label', { className: 'fld' }, 'Rendered'));
  right.appendChild(imgEl(res.pngBase64));
  right.appendChild(el('label', { className: 'fld', style: 'margin-top:10px' }, 'Tips checklist (tick by eye)'));
  const ul = el('ul', { className: 'checklist' });
  const items = checklistItems(tipsBlock);
  if (!items.length) ul.appendChild(el('li', { className: 'spinner' }, 'no tips yet — add some above'));
  for (const it of items) {
    const li = el('li');
    const cb = el('input', { type: 'checkbox' }) as HTMLInputElement;
    li.append(cb, document.createTextNode(it));
    li.onclick = (e) => {
      if (e.target !== cb) cb.checked = !cb.checked;
    };
    ul.appendChild(li);
  }
  right.appendChild(ul);
  grid.appendChild(right);
  host.appendChild(grid);

  // proof the edit reached the model (F2/F6)
  const det = el('details');
  det.appendChild(el('summary', {}, 'Injected guidance + resolved prompt (what was sent)'));
  det.appendChild(el('label', { className: 'fld' }, 'Injected tips'));
  det.appendChild(el('pre', {}, escapeHtml(res.injectedTips || '(none)')));
  det.appendChild(el('label', { className: 'fld' }, 'Resolved prompt'));
  det.appendChild(el('pre', {}, escapeHtml(res.resolvedPrompt)));
  host.appendChild(det);
}

// ---- persisted gallery view (no live run) ----------------------------------
/**
 * Show a prompt's PERSISTED output (DGMO + render from build-gallery.mjs) — the
 * default when you click a prompt, so every type×prompt is inspectable without
 * spending a `claude -p` run. `entry` is null for new/unvalidated prompts.
 */
function renderGalleryEntry(
  host: HTMLElement,
  entry: GalleryEntry | null,
  promptText: string,
  type: string
): void {
  host.innerHTML = '';
  const { glyph, label } = validationStatus(promptText);
  const badge = el('div', { className: 'pbadge' }, `${glyph} ${label}`);
  badge.style.color =
    glyph === '✓' ? 'var(--good)' : glyph === '•' ? 'var(--muted)' : 'var(--warn)';
  host.appendChild(badge);
  host.appendChild(
    el(
      'div',
      { className: 'count', style: 'margin:2px 0 8px' },
      'Saved DGMO + render for this prompt (no live run). Edit the prompt above and hit Run to regenerate live.'
    )
  );

  if (!entry || !entry.dgmo) {
    host.appendChild(
      el(
        'p',
        { className: 'spinner' },
        'No saved output for this prompt yet — it’s newly added or unvalidated. Use Run to generate it live.'
      )
    );
    return;
  }

  const grid = el('div', { className: 'result' });
  // left: DGMO source + copy
  const left = el('div');
  const srcHead = el('div', { className: 'row', style: 'align-items:center;gap:8px' });
  srcHead.appendChild(el('label', { className: 'fld', style: 'margin:0' }, 'Saved DGMO'));
  const copyBtn = el('button', {
    className: 'btn ghost narrow',
    textContent: '⧉ Copy',
    style: 'flex:none;padding:3px 10px',
  }) as HTMLButtonElement;
  copyBtn.onclick = async () => {
    try {
      await navigator.clipboard.writeText(entry.dgmo);
      copyBtn.textContent = '✓ Copied';
      setTimeout(() => (copyBtn.textContent = '⧉ Copy'), 1200);
    } catch {
      copyBtn.textContent = '✗ failed';
      setTimeout(() => (copyBtn.textContent = '⧉ Copy'), 1500);
    }
  };
  srcHead.appendChild(copyBtn);
  left.appendChild(srcHead);
  left.appendChild(el('pre', { style: 'margin-top:4px' }, escapeHtml(entry.dgmo)));
  if (entry.error) left.appendChild(el('p', { className: 'diag' }, escapeHtml(entry.error)));
  grid.appendChild(left);
  // right: rendered image (served static from /gallery)
  const right = el('div');
  right.appendChild(el('label', { className: 'fld' }, 'Saved render'));
  const box = el('div', { className: 'img' });
  if (entry.img) {
    const im = el('img') as HTMLImageElement;
    im.src = `/gallery/${entry.img}`;
    im.alt = `${type} — ${promptText}`;
    box.appendChild(im);
  } else {
    box.appendChild(
      el('span', { className: 'spinner', textContent: entry.error ? 'render failed' : 'no image' })
    );
  }
  right.appendChild(box);
  grid.appendChild(right);
  host.appendChild(grid);
}

// ---- Phase-2 N=3 before/after compare --------------------------------------
async function runCompare(
  host: HTMLElement,
  prompt: HTMLInputElement,
  dsSelect: HTMLSelectElement,
  tips: HTMLTextAreaElement,
  type: string
): Promise<void> {
  const N = 3; // fixed (Occam O3)
  host.innerHTML = '';
  const note = el(
    'p',
    { className: 'spinner' },
    `Same prompt + dataset, ${N}× each: with NO tips vs WITH your tips. Thumbnails appear as runs return.`
  );
  host.appendChild(note);

  const makeArm = (title: string): { grid: HTMLElement; slots: HTMLElement[] } => {
    host.appendChild(el('div', { className: 'arm-title' }, title));
    const grid = el('div', { className: 'grid3' });
    const slots: HTMLElement[] = [];
    for (let i = 0; i < N; i++) {
      const s = el('div', { className: 'img' });
      s.appendChild(el('span', { className: 'spinner', textContent: '…' }));
      slots.push(s);
      grid.appendChild(s);
    }
    host.appendChild(grid);
    return { grid, slots };
  };

  const before = makeArm('No guidance');
  const after = makeArm('With your tips');

  const fire = (arm: { slots: HTMLElement[] }, overrideTips: string): Promise<void>[] =>
    arm.slots.map(async (slot, i) => {
      void i;
      try {
        const res: RunResult = await fetch('/studio/run', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            type,
            prompt: prompt.value,
            datasetId: dsSelect.value || undefined,
            tips: overrideTips,
          }),
        }).then((x) => x.json());
        slot.replaceWith(decorateThumb(res));
      } catch {
        slot.innerHTML = '<span class="spinner">failed</span>';
      }
    });

  const afterTips = tips.value.trim() ? composeTips(tips.value) : '';
  await Promise.all([...fire(before, ''), ...fire(after, afterTips)]);
  note.textContent = 'Done. Eyeball the two columns: did your tips make the diagrams better?';
}

function decorateThumb(res: RunResult): HTMLElement {
  const box = el('div', { className: 'img' });
  if (res.pngBase64) {
    const img = el('img') as HTMLImageElement;
    img.src = `data:image/png;base64,${res.pngBase64}`;
    img.title = res.dgmo;
    box.appendChild(img);
  } else {
    box.appendChild(el('span', { className: 'spinner', textContent: res.error ? 'parse error' : 'no image' }));
  }
  return box;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ---- boot ------------------------------------------------------------------
renderPicker();
emptyState();
